hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8282/eureka/
